### ISSUE TITLE
Impossible to use certain stock symbols

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel-stocks#1]
```
12:57:04 <+RhinosF1> .stock LON:LGEN
12:57:05 <+MirahezeBotBeta> Invalid Symbol
```

https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=LON:LGEN&apikey={api_key} works fine

**Comment by RustyBower** [comment]
Fixed in https://github.com/RustyBower/sopel-stocks/commit/3065ce0d68e38543ededd988aa852f1776986ce5
